<?php

namespace AppBundle\Repository;

/**
 * FaktumTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaktumTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
