#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

stabam_api:
    type: rest
    prefix: /api/v1
    resource: "@AppBundle/Resources/config/persons_routes.yml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
